### ISSUE TITLE
Can't Access WebUI within specified local network

### ISSUE THREAD

**Issue by davidfrickert** [Trigus42/alpine-qbittorrentvpn#13]
Hey. Thanks for publishing this docker image for multiple archs.
Trying it out on my raspbery pi 4 aarch64.

I'm having issues acessing WebUI within the specified local network 

docker-compose.yml:
```
version: "3.7"
services:
  qbittorrent:
    image: trigus42/qbittorrentvpn
    container_name: qbittorrent
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=948
      - PGID=948
      - UMASK=003
      - VPN_ENABLED=yes
      - VPN_TYPE=openvpn
      - LAN_NETWORK=192.168.0.0/24
    volumes:
      - ./config:/config
      - /media/hdd/Media/.torrents/qB/1:/downloads
    ports:
      - 6111:6111
      - 6111:6111/udp
      - 8080:8080
    restart: unless-stopped
```

I got no errors on docker logs... I got this on the 03-network script which seems to be the one that should do the magic to allow local net access:

```
[cont-init.d] 03-network: executing...
2022-01-16 17:48:50 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2022-01-16 17:48:50 Initialization Sequence Completed
2022-01-16 17:48:50 [INFO] Docker network defined as 172.31.0.0/16
2022-01-16 17:48:50 [INFO] Adding 192.168.0.0/24 as route via docker eth0
[cont-init.d] 03-network: exited 0.
```

Any idea on why I can't access WebUI?

**Comment by Trigus42** [comment]
Can you post a screenshot of the error you get in your browser when you are trying to access the WEB UI?

**Comment by davidfrickert** [comment]
Yeah no problem @Trigus42 ! 
I get this:

![imagem](https://user-images.githubusercontent.com/25358815/149820312-f4469dcf-e33b-4172-8cf7-506204da601d.png)

**Comment by Trigus42** [comment]
You defined the subnet your clients are on as `192.168.0.0/24` while it's certainly not uncommon to have more than one subnet in your LAN, could it be that either `LAN_NETWORK=192.168.0.0/24` or the IP you entered in your client's browser are wrong?

**Comment by davidfrickert** [comment]
Humm maybe? I don't think so. The IP is definitely correct as i've got it in static IP.
The LAN network I also think it's correct:

Output from my PC:
```
 inet 192.168.1.12/24 brd 192.168.1.255 scope global dynamic
```

Output from raspberry pi (where the container is):
```
 inet 192.168.1.100/24 brd 192.168.1.255 scope global eth0
```

**Comment by Trigus42** [comment]
Maybe try `LAN_NETWORK=192.168.1.0/16` and don't forget to recreate the container (`docker-compose up -d`). Just restarting won't do

**Comment by davidfrickert** [comment]
Well, I went around and checked how I could enable iptables mangle and now it works!
It seems that maybe without that part, the webUI will never be acessible?

I essentially just did `sudo modprobe xt_mark iptable_mangle` on my host, recriated the container, and now it's accessible.

**Comment by Trigus42** [comment]
It should work without `SET_FWMARK` but if that works for you, that's great

**Comment by davidfrickert** [comment]
Ehhhh.... I can access the page but it's clearly missing alot of information, such as the torrents, download / upload speeds etc..
I guess I'll just keep using flood for webui instead of using this

**Comment by davidfrickert** [comment]
![imagem](https://user-images.githubusercontent.com/25358815/150660423-d23f52de-e4cb-4682-8e7b-2574b15c31b9.png)

**Comment by davidfrickert** [comment]
Ah. I now know why it wasn't working. I was using a port that wasn't 8080. And changed back to it, that's why it started working (even if it still doesn't fully work as the webui is unusable sadly)
