### ISSUE TITLE
Timestamps in qbittorrent.log are UTC, would love to have them in my local timezone.

### ISSUE THREAD

**Issue by antonkvm** [Trigus42/alpine-qbittorrentvpn#14]
Hi, first of all thanks a lot for making this image, all the other qbittorrentvpn images did not support my CPU architecture. It's been great so far, only ran into the one issue of the container restarting itself sometimes but a reboot of my Pi seemed to have fixed that problem.

I've noticed that the log file in `/data/logs/qbittorrent.log` are timestamped using the UTC timezone. It's not a big deal at all but if there is a way to apply my local timezone, that would be great. Maybe by passing in a `TZ` environment variable when creating the container, which I've tried but to no avail.

**Comment by Trigus42** [comment]
I've added support for setting timezones (https://github.com/Trigus42/alpine-qbittorrentvpn/commit/261f4e166a7e977b8b8550a29c1262f45088205b) you can pull the latest image and try it out.

**Comment by antonkvm** [comment]
That did the trick, thanks!
