### ISSUE TITLE
Container just exits (Wireguard, Raspberry Pi 4)

### ISSUE THREAD

**Issue by inertia666** [Trigus42/alpine-qbittorrentvpn#19]
```
qbittorrent    | Warning: `/config/wireguard/wgvpn0.conf' is world accessible
qbittorrent    | [#] ip link add wgvpn0 type wireguard
qbittorrent    | [#] wg setconf wgvpn0 /dev/fd/63
qbittorrent    | [#] ip -4 address add 10.34.45.253/16 dev wgvpn0
qbittorrent    | [#] ip link set mtu 1420 up dev wgvpn0
qbittorrent    | [#] resolvconf -a wgvpn0 -m 0 -x
qbittorrent    | [#] wg set wgvpn0 fwmark 51820
qbittorrent    | [#] ip -6 route add ::/0 dev wgvpn0 table 51820
qbittorrent    | [#] ip -6 rule add not fwmark 51820 table 51820
qbittorrent    | [#] ip -6 rule add table main suppress_prefixlength 0
qbittorrent    | [#] resolvconf -d wgvpn0 -f
qbittorrent    | [#] ip -6 rule delete table 51820
qbittorrent    | [#] ip -6 rule delete table main suppress_prefixlength 0
qbittorrent    | [#] ip link delete dev wgvpn0
qbittorrent    | [cont-init.d] 02-vpn.sh: exited 1.
qbittorrent    | [cont-finish.d] executing container finish scripts...
qbittorrent    | [cont-finish.d] done.
qbittorrent    | [s6-finish] waiting for services.
qbittorrent    | [s6-finish] sending all processes the TERM signal.
qbittorrent    | [s6-finish] sending all processes the KILL signal and exiting.
```

No errors so unsure what the problem is.

**Comment by davidfrickert** [comment]
> qbittorrent    | [cont-init.d] 02-vpn.sh: exited 1.

This step failed, with exit code 1

**Comment by Trigus42** [comment]
Can you try your wgvpn0.conf with wg-quick on another Linux machine or container?
Also your docker-compose file and a full log would be helpful.

If you want to, you can upload your wgvpn0.conf, your docker-compose and your log file [here](https://nc.taube.ovh/s/4PGgTrwjsejC8XC). This might speed up things a bit as I can diagnose the issue on my own. Ofc I would recommend you to renew/invalidate your Wireguard config after this issue is fixed.

**Comment by inertia666** [comment]
Sorry for the late reply. I have gone back to OpenVPN in the meantime after discovering from your documentation there  may be issues using Wireguard.

I was curious to test if Wireguard gave better performace on my Raspberry Pi 4.

I do not have additional Linux setups to test , unfortunately.

**Comment by almereyda** [comment]
For others landing here, like me:

Removing all IPv6-related configuration from `wg0.conf` helped me to resolve this issue.

In trying to debug the issue any further, I had also tried to replicate the additions introduced by:

- https://github.com/linuxserver/docker-wireguard/issues/208
- https://github.com/linuxserver/docker-wireguard/pull/209

to their setup (`apk add ip6tables`), but it was just not enough to get it working, neither did duplicating the configuration tips from https://github.com/DyonR/docker-qbittorrentvpn#wireguard-ipv6-issues nor setting `net.ipv6.conf.all.forwarding=1` alone.

At some point we might want to come back here to completely supporting IP connectivity also via contemporary protocols.
