### ISSUE TITLE
VPN_PORT not found in ovpn file

### ISSUE THREAD

**Issue by Fischy667** [Trigus42/alpine-qbittorrentvpn#3]
Although the VPN port is defined in the ovpn config file:

![image](https://user-images.githubusercontent.com/30476701/129560397-7edce3c1-2f21-4ae9-9a81-51def84cab40.png)

it is not found by the container:

![image](https://user-images.githubusercontent.com/30476701/129560450-9acd3378-6e40-4b3c-8961-a1b7fc26c8bc.png)

**Comment by Trigus42** [comment]
The port needs to part of the remote line. For example:
```
client
dev tun
proto udp
remote fra.whiskergalaxy.com 443
verify-x509-name fra.windscribe.com name

[...]
```

**Comment by Fischy667** [comment]
Thanks, but now I get another error.

![image](https://user-images.githubusercontent.com/30476701/129562479-43caa174-6d28-4502-bf27-86ab3776564e.png)

**Comment by Trigus42** [comment]
This means that [openvpn as provided by the apk sources ](https://pkgs.alpinelinux.org/package/edge/main/x86/openvpn) can't read your config file.

Did you write the config file yourself or was it generated by your VPN provider?
If so, can you share it here (except of course, any keys or credentials)?

**Comment by Fischy667** [comment]
It was downloaded from my vpn-provider (VPN Unlimited), but I have to add the port myself.

Attached is the version directly from the provider. (without keys)

[fr_openvpn.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/6992257/fr_openvpn.txt)

**Comment by Trigus42** [comment]
Your config file seems ok and I can't reproduce your issue..

If your host system has selinux check out this answer: https://unix.stackexchange.com/a/162789/415995

**Comment by Fischy667** [comment]
I'm running your container on a Synology NAS.

**Comment by Trigus42** [comment]
Please run and post the output of those commands:

```
$ docker run --privileged --rm -v /volume1/docker/qBittorrent_VPN_trigus/config:/config -it trigus42/qbittorrentvpn bash
```
In the container:
```
$ ls -alZ /config/openvpn

$ cd /config/openvpn
$ openvpn --config /config/openvpn/myconfig.ovpn --verb 4
```

**Comment by Fischy667** [comment]
```
bash-5.1# ls -la /config/openvpn
total 8
drwxrwxr-x    1 1000     1000            42 Aug 16 18:42 .
drwxrwxrwx    1 1026     users           14 Aug 16 11:30 ..
drwxrwxr-x    1 1000     1000            56 Aug 16 12:16 @eaDir
-rwxrwxr-x    1 1000     1000          5531 Aug 16 18:42 fr_openvpn.ovpn
```

```
bash-5.1# openvpn --config /config/openvpn/fr_openvpn.ovpn --verb 4
Options error: In [CMD-LINE]:1: Error opening configuration file: /config/openvpn/fr_openvpn.ovpn
Use --help for more information.
```

**Comment by Trigus42** [comment]
Maybe try this workaround: https://community.synology.com/enu/forum/1/post/143863
Other than that, I don't think I can't help you with this issue because I don't have a Synology NAS or any experience with one.

**Comment by Fischy667** [comment]
Yes, thanks. The problem was the --privileged in the docker command. Removing this and activating high priority manually over the docker gui was the solution.
