### ISSUE TITLE
qbittorrent will not start since qbt4.6.0-20231111

### ISSUE THREAD

**Issue by robergej** [Trigus42/alpine-qbittorrentvpn#44]
Hello! Long time user of this docker image, absolutely love using it.

I use it with wireguard, on a raspberry pi 3 (ARM64)

The last version that has worked for me is qbt4.6.0-20231108, every subsequent version has not worked. I don't think wireguard connects and the container goes into a restart loop.

Here is my docker run command:

sudo docker run --privileged -d \
    -v /docker/qbittrigus460/config/:/config \
    -v /mnt/downloads/NAS/:/NAS \
	-e "PUID=33" -e "PGID=33" \
	-e "VPN_ENABLED=yes" -e "VPN_TYPE=wireguard" \
	-e "LAN_NETWORK=192.168.86.0/24,10.180.88.0/24" \
	-e TZ=America/Montreal \
	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
	-p 8081:8080 --restart always \
	--name qbittorrenttrigus trigus42/qbittorrentvpn:qbt4.6.1-20231121

And here is the log: (these log entries just repeat endlessly as the container restarts and the same thing happens)

```
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-environment.sh: executing... 
2023-11-21 09:39:49 [INFO] LAN_NETWORK defined as '192.168.86.0/24,10.180.88.0/24'
2023-11-21 09:39:49 [INFO] Docker network defined as 172.17.0.0/16
2023-11-21 09:39:49 [INFO] PUID defined as 33
2023-11-21 09:39:49 [INFO] PGID defined as 33
2023-11-21 09:39:49 [INFO] An user with PUID 33 already exists in /etc/passwd, nothing to do.
2023-11-21 09:39:49 [INFO] VPN_ENABLED defined as 'yes'
2023-11-21 09:39:49 [INFO] VPN_TYPE defined as 'wireguard'
2023-11-21 09:39:49 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers
2023-11-21 09:39:49 [INFO] Adding 1.1.1.1 to resolv.conf
2023-11-21 09:39:49 [INFO] Adding 8.8.8.8 to resolv.conf
2023-11-21 09:39:49 [INFO] Adding 1.0.0.1 to resolv.conf
2023-11-21 09:39:49 [INFO] Adding 8.8.4.4 to resolv.conf
[cont-init.d] 01-environment.sh: exited 0.
[cont-init.d] 02-vpn.sh: executing... 
2023-11-21 09:39:49 [INFO] Choosen VPN config: 'wg0.conf'
dos2unix: converting file /config/wireguard/wg0.conf to Unix format...
2023-11-21 09:39:49 [INFO] VPN remote line defined as 'ca.vpn.airdns.org:1637'
2023-11-21 09:39:49 [INFO] VPN_REMOTE defined as 'ca.vpn.airdns.org'
2023-11-21 09:39:49 [INFO] VPN_PORT defined as '1637'
2023-11-21 09:39:49 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.
2023-11-21 09:39:49 [INFO] VPN_DEVICE_TYPE set as 'wg0'
2023-11-21 09:39:49 [INFO] Starting WireGuard...
--------------------
Warning: `/config/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.157.143.242/32 dev wg0
[#] ip -6 address add fd7d:76ee:e68f:a993:1260:fe9a:afb4:5dc0/128 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -6 route add ::/0 dev wg0 table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] ip6tables-restore -n
/usr/bin/wg-quick: line 32: ip6tables-restore: command not found
[#] resolvconf -d wg0 -f
[#] ip -6 rule delete table 51820
[#] ip -6 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
[cont-init.d] 02-vpn.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
```

Thank you!

**Comment by Trigus42** [comment]
Does it still work with the old image? 
My guess would be that your VPN provider might have added an IPv6 address to the VPN server you are using or IPv6 is now enabled for you docker network or something similar. Now your client tries to use IPv6 to communicate with the VPN server. Thats why wg-quick tries to add mangle rules to mark and correctly route the Wireguard packets. However, ip6tables-restore can't be found cause ip6tables is not a subpackage of iptables in alpine.

Even if I were to add ip6tables to the container, this won't just work cause the firewall in this container won't allow IPv6 wireguard connections (over eth0) and the firewall won't allow IPv6 packets over wg0 (this wouldn't cause an error but IPv6 still wouldn't be usable).

However, I created a new branch "[nftables](https://github.com/Trigus42/alpine-qbittorrentvpn/tree/nftables)" with the according image being `trigus42/qbittorrentvpn:nftables` that also adds support for IPv6. You also have to [enable IPv6 for your docker daemon](https://docs.docker.com/config/daemon/ipv6/) if you want to not only use IPv6 over the VPN but also use IPv6 to communicate with the VPN server.

For a simpler solution you could try removing `--sysctl net.ipv6.conf.all.disable_ipv6=0` from you docker command and maybe also `::0` from the AllowedIPs in your Wireguard config.

**Comment by robergej** [comment]
Thanks for the rapid response!

Yes it does still work with older images. I'm using the last 4.5.5 image now still without issues, but I also tested successfully with up to 4.6.0-20231108. newer than that and it fails to start. Each time using the exact same wireguard config file. I can't guarantee nothing has changed on my VPN provider's side but I doubt it since older images still work fine.

I will try your last solution shortly and let you know.
Thanks!

**Comment by robergej** [comment]
Thank you! Issue is resolved.

I removed --sysctl net.ipv6.conf.all.disable_ipv6=0 from my docker run command, and I generated a new wireguard config from my provider (airvpn), specifically asking for it to not include IPv6. Now the container comes up and everything seems fine. Thanks!

**Comment by Trigus42** [comment]
I figured it out btw: Up until alpine version 3.17 `ip6tables-restore` was part of `wireguard-tools`. The commit https://github.com/Trigus42/alpine-qbittorrentvpn/commit/75328d75f7cba0318af0dfad9023534af0f6306a where I upgraded the base image to version 3.18 created your issue.

**Comment by robergej** [comment]
Ah that makes sense. Thanks for the follow up I appreciate it!
