### ISSUE TITLE
"INSTALL_PYTHON3" not included anymore?

### ISSUE THREAD

**Issue by EpicLPer** [Trigus42/alpine-qbittorrentvpn#53]
I've just transferred the Docker container to a new host and noticed that the `INSTALL_PYTHON3` variable apparently isn't included anymore? At least it doesn't seem to work as of a recent update.
I tried installing some Plugins/noticed that the old plugins I had on the previous containers aren't working anymore. Installing new ones simply does nothing, similar to as if Python is not installed at all.

**Comment by EpicLPer** [comment]
Oh, I just noticed in commit 695883135de49c1b3ac07b6265c14e559138dea0 that the option was indeed removed. Is Python supposed to be included in the image now?

**Comment by EpicLPer** [comment]
I temporarily fixed this by going into the container and running `apk add --no-cache python3`, just like the old deleted installer script would've done it.

**Comment by Trigus42** [comment]
I'm sorry for the interruption that caused you. Python3 is not part of the image anymore. Please take a look at [this](https://github.com/Trigus42/alpine-qbittorrentvpn#customization) part of the README.

**Comment by EpicLPer** [comment]
Thanks for the tip! I think it would be a good idea to state this more easily in a section "Plugins" on the Readme maybe, as those require Python 3 to be installed to work.

**Comment by gderf** [comment]
The workaround specified in the readme https://github.com/Trigus42/alpine-qbittorrentvpn#customization has stopped working for me sometime around June 20, 2024. Qbt throws some errors in the log about not being able to find my script and never loads. It just goes into a retry loop but continues to fail.

Log snip:

06/22/2024
11:34:43 AM
cont-init: info: running /etc/cont-init.d/50-add-extras.sh
06/22/2024
11:34:43 AM
/package/admin/s6-overlay-3.2.0.0/etc/s6-rc/scripts/cont-init: line 20: /etc/cont-init.d/50-add-extras.sh: not found
06/22/2024
11:34:43 AM
cont-init: info: /etc/cont-init.d/50-add-extras.sh exited 127
06/22/2024
11:34:43 AM
cont-init: warning: some scripts exited nonzero
06/22/2024
11:34:43 AM
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
06/22/2024
11:34:43 AM
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
06/22/2024
11:34:43 AM
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
06/22/2024
11:34:43 AM
s6-rc: info: service fix-attrs: stopping
06/22/2024
11:34:43 AM
s6-rc: info: service fix-attrs successfully stopped
06/22/2024
11:34:43 AM
s6-rc: info: service s6rc-oneshot-runner: stopping
06/22/2024
11:34:43 AM
s6-rc: info: service s6rc-oneshot-runner successfully stopped
06/22/2024
11:34:43 AM
s6-linux-init-shutdown: fatal: unable to talk to shutdownd: Operation not permitted

**Comment by Trigus42** [comment]
Sorry you had to wait this long for a response @gderf. Please take another look at https://github.com/Trigus42/alpine-qbittorrentvpn#customization. I have updated the documentation

**Comment by gderf** [comment]
Fixed in tag c58588acf14e

Thanks

**Comment by windostechsupport** [comment]
@Trigus42 hey. I directed the volume to the script to install python3, but it won't automatically execute. If I enter the container and execute the script manually it works just fine.

**Comment by windostechsupport** [comment]
```
    volumes:
...
      - ./custom-scripts/install-packages.sh:/custom-cont-int.d/install-packages.sh
```

**Comment by Trigus42** [comment]
You've got the directory wrong. It should be `custom-cont-init.d`, not `custom-cont-int.d`
