### ISSUE TITLE
The default password does not work, how to reset it?

### ISSUE THREAD

**Issue by blixten85** [Trigus42/alpine-qbittorrentvpn#64]
As the title reads. How do i reset the default password when running this in a docker?
The logs shows nothing about any password or usernmame.

**Comment by Trigus42** [comment]
You can set a WebUI password to use for initial setup using the `WEBUI_PASSWORD` environment variable. This variable won't overwrite an existing password. 
If you didn't set a password, QBt generates a temporary password which is printed to the QBt logs (`config/qBittorrent/data/logs/qbittorrent.log`). This temporary password is changed on every restart of QBt and will be overwritten if you set `WEBUI_PASSWORD`.

You can reset an existing password by deleting the file `config/qBittorrent/config/qBittorrent.conf` or just removing the line starting with `WebUI\Password_PBKDF2=` from it.
