### ISSUE TITLE
Not an issue | Which port does the wireguard port VPN listen to?

### ISSUE THREAD

**Issue by aanwark** [Trigus42/alpine-qbittorrentvpn#72]
I am using this image in the Linux Jail on TrueNAS Scale. I have a WG server installed which listens on the default port 51820. Since I have set this instance up, my server is no longer connecting. Just a question, is there a port clash in this case meaning that the client in this image and my server listening on the same default port? Thanks!

**Comment by Trigus42** [comment]
No this shouldn't be case

**Comment by aanwark** [comment]
Thanks I figured, the issue was caused by having the server and client on same subnets.
