### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by V0l-D** [Trigus42/alpine-qbittorrentvpn#76]
Currently it's running on qbittorrent version 4.6.7 the latest version is 5.0.0, according to the docker image it's running it's latest version which is not quite right.
![image](https://github.com/user-attachments/assets/0d18b7ef-2346-460f-9959-518e1ef0275b)
![image](https://github.com/user-attachments/assets/cc175870-cf8b-402f-9f92-32f480638da5)

**Comment by Trigus42** [comment]
Thanks for bringing my attention to this! Should be fixed.

**Comment by gderf** [comment]
Fixed now. Thank you very much for this image and for making quick updates.

**Comment by gderf** [comment]
Reopening this.

When I pull the image with **latest** tag its ID differs from that of tag **qbt5.0.0**

fred@omv:~$ docker images | grep trig
trigus42/qbittorrentvpn         latest              5047d747a319   9 days ago      129MB
trigus42/qbittorrentvpn         qbt5.0.0         341bbb87cb3c   12 days ago     129MB
