### ISSUE TITLE
Latest Version?

### ISSUE THREAD

**Issue by gderf** [Trigus42/alpine-qbittorrentvpn#78]
When I pull the image with latest tag its ID differs from that of tag qbt5.0.0
```
fred@omv:~$ docker images | grep trig

trigus42/qbittorrentvpn         latest        5047d747a319   9 days ago      129MB
trigus42/qbittorrentvpn         qbt5.0.0      341bbb87cb3c   12 days ago     129MB

```

**Comment by Trigus42** [comment]
Could you please try pulling again? On DockerHub and GHCR the image digest of latest and qbt5.0.0 match:

https://hub.docker.com/layers/trigus42/qbittorrentvpn/latest/images/sha256-fb04a04f0056af547fe19394e8c346ef20e65ff6288750aa4da3ab21ef270731?context=explore

https://hub.docker.com/layers/trigus42/qbittorrentvpn/qbt5.0.0/images/sha256-fb04a04f0056af547fe19394e8c346ef20e65ff6288750aa4da3ab21ef270731?context=explore

https://github.com/Trigus42/alpine-qbittorrentvpn/pkgs/container/alpine-qbittorrentvpn/284366431?tag=latest

https://github.com/Trigus42/alpine-qbittorrentvpn/pkgs/container/alpine-qbittorrentvpn/284366431?tag=qbt5.0.0
