### ISSUE TITLE
All trackers unreachable

### ISSUE THREAD

**Issue by DBLouis** [Trigus42/alpine-qbittorrentvpn#83]
I'm using docker image 4.6.7, with wireguard VPN enabled. I can confirm that VPN connection works inside the container and DNS too. But in qbittorrent all torrent are stalled and trackers are unreachable.
I should mention that I moved from a previous install with another image (qbittorrent nox) and did not reset the config.

**Comment by DBLouis** [comment]
I fixed it. That was not a network issue but a file system permission issue. I am running the container rootless so PID 0 "inside" is my user "outside". I had to set PUID=0 and PGID=0.

**Comment by Trigus42** [comment]
Not running as PID 0 is a security feature. Although it's not a big risk, I would recommend changing ownership of the qBt volume by running `chown -R 1000:1000 CONFIG_DIR` instead.

**Comment by DBLouis** [comment]
It is PID 0 in a namespace, so not actually root on the host, that's fine.
