### ISSUE TITLE
Multiple VPNs

### ISSUE THREAD

**Issue by Y0ngg4n** [Trigus42/alpine-qbittorrentvpn#9]
Hey just wondered if it would be possible to provide multiple VPN configurations and the container chooses a random one?

**Comment by Trigus42** [comment]
I have added the feature to the dev branch. Please take a look at the updated [README](https://github.com/Trigus42/alpine-qbittorrentvpn/tree/dev#vpn-configuration) and try out the [dev image](https://hub.docker.com/layers/trigus42/qbittorrentvpn/dev-qbt4.3.9/images/sha256-18949bf5e28b13c59b833dbf276591ac6acf16355d6685045aab1f53be329264?context=explore).

**Comment by Y0ngg4n** [comment]
@Trigus42 i will test it out the next days.

**Comment by Y0ngg4n** [comment]
Seems to work
